config/routes.rb
Mysecurity::Application.routes.draw do
scope "soft/nutriendo" do

  resources :inventario_menajes

  resources :inventario_equipamientos

  resources :tipo_de_menajes

  resources :tipo_de_equipamientos

  resources :escuelas

  resources :localidads

  resources :role_permissions

    devise_for :users, :path => 'user'

    resources :roles
    resources :users

  match 'inventario_menajes/inventarios/listado_escuela/:idEscuela' => 'inventario_menajes#listado_escuela' 
  match 'inventario_menajes/inventarios/agregar_elemento_inventario' => 'inventario_menajes#agregar_elemento_inventario'
  match 'inventario_menajes/inventarios/quitar_elemento_inventario/:idElementoInventario' => 'inventario_menajes#quitar_elemento_inventario'
  match 'inventario_menajes/inventarios/modificar_elemento_inventario/' => 'inventario_menajes#modificar_elemento_inventario'

  match 'inventario_equipamientos/inventarios/listado_escuela/:idEscuela' => 'inventario_equipamientos#listado_escuela' 
  match 'inventario_equipamientos/inventarios/agregar_elemento_inventario' => 'inventario_equipamientos#agregar_elemento_inventario'
  match 'inventario_equipamientos/inventarios/quitar_elemento_inventario/:idElementoInventario' => 'inventario_equipamientos#quitar_elemento_inventario'
  match 'inventario_equipamientos/inventarios/modificar_elemento_inventario/' => 'inventario_equipamientos#modificar_elemento_inventario'

  root :to => "escuelas#index"

end
end

app/models/inventario_equipamiento.rb
class InventarioEquipamiento < ActiveRecord::Base

  attr_accessible :escuela_id, :ultima_modificacion
  has_many :renglon_inventario_equipamientos
  belongs_to :escuela

end

app/controllers/inventario_equipamientos_controller.rb
class InventarioEquipamientosController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /inventario_equipamientos
  # GET /inventario_equipamientos.json
  def index
    @inventario_equipamientos = InventarioEquipamiento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventario_equipamientos }
    end
  end

  # GET /inventario_equipamientos/1
  # GET /inventario_equipamientos/1.json
  def show
    @inventario_equipamiento = InventarioEquipamiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventario_equipamiento }
    end
  end

  # GET /inventario_equipamientos/new
  # GET /inventario_equipamientos/new.json
  def new
    @inventario_equipamiento = InventarioEquipamiento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventario_equipamiento }
    end
  end

  # GET /inventario_equipamientos/1/edit
  def edit
    @inventario_equipamiento = InventarioEquipamiento.find(params[:id])
  end

  # POST /inventario_equipamientos
  # POST /inventario_equipamientos.json
  def create
    @inventario_equipamiento = InventarioEquipamiento.new(params[:inventario_equipamiento])

    respond_to do |format|
      if @inventario_equipamiento.save
        format.html { redirect_to @inventario_equipamiento, notice: 'Inventario equipamiento was successfully created.' }
        format.json { render json: @inventario_equipamiento, status: :created, location: @inventario_equipamiento }
      else
        format.html { render action: "new" }
        format.json { render json: @inventario_equipamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventario_equipamientos/1
  # PUT /inventario_equipamientos/1.json
  def update
    @inventario_equipamiento = InventarioEquipamiento.find(params[:id])

    respond_to do |format|
      if @inventario_equipamiento.update_attributes(params[:inventario_equipamiento])
        format.html { redirect_to @inventario_equipamiento, notice: 'Inventario equipamiento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventario_equipamiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventario_equipamientos/1
  # DELETE /inventario_equipamientos/1.json
  def destroy
    @inventario_equipamiento = InventarioEquipamiento.find(params[:id])
    @inventario_equipamiento.destroy

    respond_to do |format|
      format.html { redirect_to inventario_equipamientos_url }
      format.json { head :no_content }
    end
  end

  def listado_escuela
    if params["idEscuela"] then
      @escuela = Escuela.find(params["idEscuela"].to_i)
      @inventario_equipamientos = InventarioEquipamiento.where(:escuela_id => params["idEscuela"].to_i).first
    
      if params["q"] then
        if params["q"] == "" then
          @renglon_inventario_equipamiento = @inventario_equipamientos.renglon_inventario_equipamientos
        else
          @renglon_inventario_equipamiento = @inventario_equipamientos.renglon_inventario_equipamientos.where(:tipo_de_equipamiento_id => params["q"].to_i)
        end
      else      
        @renglon_inventario_equipamiento = @inventario_equipamientos.renglon_inventario_equipamientos
      end  
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventario_equipamientos }
    end    
  end

  def agregar_elemento_inventario
    #debugger
    @inventario = params["idInventario"]
    @tipo_de_equipamiento = params["tipo_de_equipamiento"]
    @cantidad = params["cantidad"]
    if current_user then 
      #RenglonInventarioEquipamiento(id: integer, fecha_de_alta: date, cantidad: string, user: integer, inventario_equipamiento_id: integer, tipo_de_equipamiento_id: integer, quien_modifica: integer, created_at: datetime, updated_at: datetime) 
      RenglonInventarioEquipamiento.create(
                                            :cantidad => @cantidad.to_i, 
                                            :user => current_user.id, 
                                            :inventario_equipamiento_id => @inventario.to_i, 
                                            :tipo_de_equipamiento_id => @tipo_de_equipamiento.to_i
                                          )
    end
    redirect_to :back
  end
  def quitar_elemento_inventario
    #debugger
    if params["idElementoInventario"] then
      RenglonInventarioEquipamiento.find(params["idElementoInventario"].to_i).destroy
    end
    redirect_to :back
  end
  def ver_elemento_inventario
    
  end
  def modificar_elemento_inventario
    if params["pk"] and params["value"] then
      rie = RenglonInventarioEquipamiento.find(params["pk"].to_i)
      if rie then
        rie.cantidad = params["value"].to_i
        rie.save
      end
    end
  end

   
end

app/helpers/inventario_equipamientos_helper.rb
module InventarioEquipamientosHelper
end

app/views/inventario_equipamientos/_form.html.erb
<%= form_for(@inventario_equipamiento) do |f| %>
  <% if @inventario_equipamiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventario_equipamiento.errors.count, "error") %> prohibited this inventario_equipamiento from being saved:</h2>

      <ul>
      <% @inventario_equipamiento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :escuela_id %><br />
    <%= f.number_field :escuela_id %>
  </div>
  <div class="field">
    <%= f.label :ultima_modificacion %><br />
    <%= f.date_select :ultima_modificacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventario_equipamientos/edit.html.erb
<h1>Editar inventario_equipamiento</h1>

<%= render 'form' %>

<%= link_to 'ver', @inventario_equipamiento %> |
<%= link_to 'atras', inventario_equipamientos_path %>

app/views/inventario_equipamientos/index.html.erb
<h1>Listado de inventario_equipamientos</h1>

<table class="table table-striped">
  <tr>
    <th>Escuela</th>
    <th>Ultima modificacion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventario_equipamientos.each do |inventario_equipamiento| %>
  <tr>
    <td><%= inventario_equipamiento.escuela_id %></td>
    <td><%= inventario_equipamiento.ultima_modificacion %></td>
    <td><% if can? :read, InventarioEquipamiento %><%= link_to 'ver', inventario_equipamiento %><% end %></td>
    <td><% if can? :update, InventarioEquipamiento %><%= link_to 'editar', edit_inventario_equipamiento_path(inventario_equipamiento) %><% end %></td>
    <td><% if can? :destroy, InventarioEquipamiento %><%= link_to 'eliminar', inventario_equipamiento, method: :delete, data: { confirm: 'Seguro desear eliminar?' } %><% end %></td>
  </tr>
<% end %>
</table>

<br />

<% if can? :create, InventarioEquipamiento %><%= link_to 'Agregar Inventario equipamiento', new_inventario_equipamiento_path %><% end %>

app/views/inventario_equipamientos/listado_escuela.html.erb
<div class="row">
  <div class="span12">
    <p class="lead" align="center"><b>Escuela <%= @escuela.nombre %></b> N° <b><%= @escuela.numero %> de la localidad de </b> <%= @escuela.localidad %></p>
    <div class="row">
      <div class="span3">
        <ul class="nav nav-list">
          <li class="nav-header">Datos Escuela</li>
          <% if can? :read, Escuela %><li><%= link_to 'ver', @escuela %></li><% end %>
          <% if can? :update, Escuela %><li><%= link_to 'editar', edit_escuela_path(@escuela) %></li><% end %>
          <li class="nav-header">Menaje</li>
            <% if can? :read, RenglonInventarioMenaje %><li><a href="<%= url_for :controller => "inventario_menajes", :action => "listado_escuela", :idEscuela => @escuela.id %>">ver Menaje</a></li><% end %>
          <li class="nav-header">Equipamiento</li>
            <% if can? :read, RenglonInventarioEquipamiento %><li><a href="<%= url_for :controller => "inventario_equipamientos", :action => "listado_escuela", :idEscuela => @escuela.id %>">ver Equipamiento</a></li><% end %>
        </ul>
      </div>

      <form class="form-search" action="<%= url_for :controller => "inventario_equipamientos", :action => "listado_escuela"%>">
        <div >
          <div class="input-prepend">
            <button type="submit" class="btn" >Buscar</button>
          </div>
          <select name="q">
            <%TipoDeEquipamiento.all.each do |tde|%>
              <option value="<%= tde.id %>"><%= tde %></option>
            <% end %>
          </select> 
          <div class="input-append">
            <a class="btn" href="<%= url_for :controller => "inventario_equipamientos", :action => "listado_escuela"%>">Limpiar</a>
            
          </div>
        </div>
      </form>


      <div class="span9">
        <table class="table table-bordered table-striped">
            <tr>
              <th>Cantidad</th>
              <th>Tipo de equipamiento</th>
              <% if can? :destroy, RenglonInventarioEquipamiento %><th></th><% end %>
            </tr>
          <% @renglon_inventario_equipamiento.each do |rie| %>
            <tr>
              <td>
                <% if can? :update, RenglonInventarioEquipamiento %>
                  <a href="#" id="cantidad_<%= rie.id%>" name="cantidad" data-type="text" data-pk="<%=rie.id%>" data-url="<%= url_for :controller => "inventario_equipamientos", :action => "modificar_elemento_inventario" %>" name="cantidad" data-original-title="Ingrese cantidad"><%= rie.cantidad %></a>
                <% elsif can? :read, RenglonInventarioEquipamiento %>
                  <%= rie.cantidad %>
                <% end %>
              </td>
              <td><%= rie.tipo_de_equipamiento %></td>
              <!--inventario_equipamientos#quitar_elemento_inventario-->
              <% if can? :destroy, RenglonInventarioEquipamiento %><td><a href="<%= url_for :controller => "inventario_equipamientos", :action => "quitar_elemento_inventario", :idElementoInventario => rie.id %>" onclick="return confirm('Realmente desea eliminar?')"> <span class="badge badge-important"> eliminar </span></a></td><% end %>
            </tr>
          <% end %>
          <% @renglon_inventario_equipamiento.each do |rie| %>
            <script type="text/javascript">
               $('#cantidad_<%= rie.id%>').editable({
                  type: 'text',
                  pk: 1,
                  url: '#',
                  title: 'Ingrese cantidad',
                  mode: 'inline'
               });
            </script>
          <% end %>
          </table>
          <br />

          <% if can? :create, RenglonInventarioEquipamiento %><a href="#myModal" role="button" data-toggle="modal"><span class="badge badge-success">Agregar equipamiento</span></a><% end %>
      </div>
   </div>
  </div>
</div>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Agregar Equipamiento al Inventario</h3>
  </div>
  <div class="modal-body">
    <form action="<%=url_for :controller => "inventario_equipamientos", :action => "agregar_elemento_inventario"%>" >
      <input type="hidden" id="idInventario" name="idInventario" value="<%=@inventario_equipamientos.id%>">
      <input type="text" id="cantidad" name="cantidad" placeholder="cantidad" class="input-mini">
      <select id="tipo_de_equipamiento" name="tipo_de_equipamiento">
        <% TipoDeEquipamiento.all.each do |tde|%>
          <option value="<%= tde.id %>"><%= tde %></option>
        <% end %>
      </select>
      <input type="submit" value="agregar al inventario" class="btn btn-primary">
    </form>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
  </div>
</div>

app/views/inventario_equipamientos/new.html.erb
<h1>Agregar inventario_equipamiento</h1>

<%= render 'form' %>

<%= link_to 'atras', inventario_equipamientos_path %>

app/views/inventario_equipamientos/show.html.erb
<p id="notice"><%= notice %></p>

<% @escuela = Escuela.where(:id => @inventario_equipamiento.escuela_id).first %>

<p><h2>Inventario Escuela <%= @inventario_equipamiento.escuela %> - <%= @escuela.localidad %></h2></p>

<p>
  <b>Escuela:</b>
  <%= @inventario_equipamiento.escuela %>
</p>

<p>
  <b>Ultima modificacion:</b>
  <%= @inventario_equipamiento.ultima_modificacion %>
</p>


<a href="#myModal" role="button" class="btn btn-success" data-toggle="modal">Agregar Inventario Equipamiento</a>


<!-- <form action="<%= url_for :controller =>  "inventario_equipamientos", :action => "agregar_renglon_inventario_equipamientos" %>"> -->

    <!-- Modal -->
    <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Nuevo inventario de equipamiento</h3>
      </div>
      <div class="modal-body">
        
        
          <label>Cantidad</label>
          <input type="text_field" id="cantidad"></br>
          <label>Fecha de alta</label>
          <input type="text_field" id="fecha_de_alta"></br>
          <label>Inventario equipamiento id</label>
          <input type="text_field" id="inventario_equipamiento_id"></br>
          <label>Quien Modifica</label>
          <input type="text_field" id="quien_modifica"></br>
          <label>Tipo de Equipamiento</label>
          <input type="text_field" id="tipo_de_equipamiento_id"></br>
          <label>Usuario</label>
          <input type="text_field" id="user"></br>
    
        
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
       <!--  <input type="submit" class="btn btn-primary" name="agregar renglon inventario equipamiento" value="Guardar"> -->
        <a href="<%=url_for inventario_equipamientos_agregar_renglon_inventario_equipamientos_path%>/<%=@inventario_equipamiento.id%>" ><i class="btn btn-primary">Guardar</i>
       <!--  <button class="btn btn-primary" type="submit" name="cargar renglon inventario equipamiento" >Guardar</button> -->
      </div>
    </div> 

<!-- </form> -->

</br></br>

<%= link_to 'Editar', edit_inventario_equipamiento_path(@inventario_equipamiento) %> |
<%= link_to 'Volver', inventario_equipamientos_path %>