config/routes.rb
Mysecurity::Application.routes.draw do
scope "soft/nutriendo" do

  resources :inventario_menajes

  resources :inventario_equipamientos

  resources :tipo_de_menajes

  resources :tipo_de_equipamientos

  resources :escuelas

  resources :localidads

  resources :role_permissions

    devise_for :users, :path => 'user'

    resources :roles
    resources :users

  match 'inventario_menajes/inventarios/listado_escuela/:idEscuela' => 'inventario_menajes#listado_escuela' 
  match 'inventario_menajes/inventarios/agregar_elemento_inventario' => 'inventario_menajes#agregar_elemento_inventario'
  match 'inventario_menajes/inventarios/quitar_elemento_inventario/:idElementoInventario' => 'inventario_menajes#quitar_elemento_inventario'
  match 'inventario_menajes/inventarios/modificar_elemento_inventario/' => 'inventario_menajes#modificar_elemento_inventario'

  match 'inventario_equipamientos/inventarios/listado_escuela/:idEscuela' => 'inventario_equipamientos#listado_escuela' 
  match 'inventario_equipamientos/inventarios/agregar_elemento_inventario' => 'inventario_equipamientos#agregar_elemento_inventario'
  match 'inventario_equipamientos/inventarios/quitar_elemento_inventario/:idElementoInventario' => 'inventario_equipamientos#quitar_elemento_inventario'
  match 'inventario_equipamientos/inventarios/modificar_elemento_inventario/' => 'inventario_equipamientos#modificar_elemento_inventario'

  root :to => "escuelas#index"

end
end

app/models/inventario_menaje.rb
class InventarioMenaje < ActiveRecord::Base
  attr_accessible :escuela_id, :ultima_modificacion
  has_many :renglon_inventario_menajes
  belongs_to :escuela
end

app/controllers/inventario_menajes_controller.rb
class InventarioMenajesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /inventario_menajes
  # GET /inventario_menajes.json
  def index
    @inventario_menajes = InventarioMenaje.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventario_menajes }
    end
  end

  # GET /inventario_menajes/1
  # GET /inventario_menajes/1.json
  def show
    @inventario_menaje = InventarioMenaje.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventario_menaje }
    end
  end

  # GET /inventario_menajes/new
  # GET /inventario_menajes/new.json
  def new
    @inventario_menaje = InventarioMenaje.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventario_menaje }
    end
  end

  # GET /inventario_menajes/1/edit
  def edit
    @inventario_menaje = InventarioMenaje.find(params[:id])
  end

  # POST /inventario_menajes
  # POST /inventario_menajes.json
  def create
    @inventario_menaje = InventarioMenaje.new(params[:inventario_menaje])

    respond_to do |format|
      if @inventario_menaje.save
        format.html { redirect_to @inventario_menaje, notice: 'Inventario menaje was successfully created.' }
        format.json { render json: @inventario_menaje, status: :created, location: @inventario_menaje }
      else
        format.html { render action: "new" }
        format.json { render json: @inventario_menaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventario_menajes/1
  # PUT /inventario_menajes/1.json
  def update
    @inventario_menaje = InventarioMenaje.find(params[:id])

    respond_to do |format|
      if @inventario_menaje.update_attributes(params[:inventario_menaje])
        format.html { redirect_to @inventario_menaje, notice: 'Inventario menaje was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inventario_menaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventario_menajes/1
  # DELETE /inventario_menajes/1.json
  def destroy
    @inventario_menaje = InventarioMenaje.find(params[:id])
    @inventario_menaje.destroy

    respond_to do |format|
      format.html { redirect_to inventario_menajes_url }
      format.json { head :no_content }
    end
  end

  def listado_escuela
    if params["idEscuela"] then
      @escuela = Escuela.find(params["idEscuela"].to_i)
      @inventario_menajes = InventarioMenaje.where(:escuela_id => params["idEscuela"].to_i).first
    
      if params["q"] then
        if params["q"] == "" then
          @renglon_inventario_menaje = @inventario_menajes.renglon_inventario_menajes
        else
          @renglon_inventario_menaje = @inventario_menajes.renglon_inventario_menajes.where(:tipo_de_menaje_id => params["q"].to_i)
        end
      else      
        @renglon_inventario_menaje = @inventario_menajes.renglon_inventario_menajes
      end  
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventario_menajes }
    end    
  end

  def agregar_elemento_inventario
    #debugger

    @inventario = params["idInventario"]
    @tipo_de_menaje = params["tipo_de_menaje"]
    @cantidad = params["cantidad"]
    if current_user then 
      #RenglonInventarioEquipamiento(id: integer, fecha_de_alta: date, cantidad: string, user: integer, inventario_equipamiento_id: integer, tipo_de_menaje_id: integer, quien_modifica: integer, created_at: datetime, updated_at: datetime) 
      RenglonInventarioMenaje.create(
                                            :cantidad => @cantidad.to_i, 
                                            :user => current_user.id, 
                                            :inventario_menaje_id => @inventario.to_i, 
                                            :tipo_de_menaje_id => @tipo_de_menaje.to_i
                                          )
    end
    redirect_to :back
  end

  def quitar_elemento_inventario
    #debugger
    if params["idElementoInventario"] then
      RenglonInventarioMenaje.find(params["idElementoInventario"].to_i).destroy
    end
    redirect_to :back
  end
  
  def ver_elemento_inventario
    
  end
  
  def modificar_elemento_inventario
    if params["pk"] and params["value"] then
      rie = RenglonInventarioMenaje.find(params["pk"].to_i)
      if rie then
        rie.cantidad = params["value"].to_i
        rie.save
      end
    end
  end

end

app/helpers/inventario_menajes_helper.rb
module InventarioMenajesHelper
end

app/views/inventario_menajes/_form.html.erb
<%= form_for(@inventario_menaje) do |f| %>
  <% if @inventario_menaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventario_menaje.errors.count, "error") %> prohibited this inventario_menaje from being saved:</h2>

      <ul>
      <% @inventario_menaje.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :escuela_id %><br />
    <%= f.number_field :escuela_id %>
  </div>
  <div class="field">
    <%= f.label :ultima_modificacion %><br />
    <%= f.date_select :ultima_modificacion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventario_menajes/edit.html.erb
<h1>Editar inventario_menaje</h1>

<%= render 'form' %>

<%= link_to 'ver', @inventario_menaje %> |
<%= link_to 'atras', inventario_menajes_path %>

app/views/inventario_menajes/index.html.erb
<h1>Listado de inventario_menajes</h1>

<table class="table table-striped">
  <tr>
    <th>Escuela</th>
    <th>Ultima modificacion</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inventario_menajes.each do |inventario_menaje| %>
  <tr>
    <td><%= inventario_menaje.escuela_id %></td>
    <td><%= inventario_menaje.ultima_modificacion %></td>
    <td><%= link_to 'ver', inventario_menaje %></td>
    <td><%= link_to 'editar', edit_inventario_menaje_path(inventario_menaje) %></td>
    <td><%= link_to 'eliminar', inventario_menaje, method: :delete, data: { confirm: 'Desea eliminar?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Agregar Inventario menaje', new_inventario_menaje_path %>

app/views/inventario_menajes/listado_escuela.html.erb
<div class="row">
  <div class="span12">
    <p class="lead" align="center"><b>Escuela <%= @escuela.nombre %></b> N° <b><%= @escuela.numero %> de la localidad de </b> <%= @escuela.localidad %></p>
    <div class="row">
      <div class="span3">
        <ul class="nav nav-list">
          <li class="nav-header">Datos Escuela</li>
          <% if can? :read, Escuela %><li><%= link_to 'ver', @escuela %></li><% end %>
          <% if can? :update, Escuela %><li><%= link_to 'editar', edit_escuela_path(@escuela) %></li><% end %>
          <li class="nav-header">Menaje</li>
            <% if can? :read, RenglonInventarioMenaje %><li><a href="<%= url_for :controller => "inventario_menajes", :action => "listado_escuela", :idEscuela => @escuela.id %>">ver Menaje</a></li><% end %>
          <li class="nav-header">Equipamiento</li>
            <% if can? :read, RenglonInventarioEquipamiento %><li><a href="<%= url_for :controller => "inventario_equipamientos", :action => "listado_escuela", :idEscuela => @escuela.id %>">ver Equipamiento</a></li><% end %>
        </ul>
      </div>

      <form class="form-search" action="<%= url_for :controller => "inventario_menajes", :action => "listado_escuela"%>">
        <div >
          <div class="input-prepend">
            <button type="submit" class="btn" >Buscar</button>
          </div>
          <select name="q">
            <%TipoDeMenaje.all.each do |tdm|%>
              <option value="<%= tdm.id %>"><%= tdm %></option>
            <% end %>
          </select> 
          <div class="input-append">
            <a class="btn" href="<%= url_for :controller => "inventario_menajes", :action => "listado_escuela"%>">Limpiar</a>
          </div>
        </div>
      </form>
      
      <div class="span9">
        <table class="table table-bordered table-striped">
            <tr>
              <th>Cantidad</th>
              <th>Tipo de Menaje</th>
              <% if can? :destroy, RenglonInventarioMenaje %><th></th><% end %>
            </tr>
          <% @renglon_inventario_menaje.each do |rim| %>
            <tr>
              <td>
                <% if can? :update, RenglonInventarioMenaje %>
                  <a href="#" id="cantidad_<%= rim.id%>" name="cantidad" data-type="text" data-pk="<%=rim.id%>" data-url="<%= url_for :controller => "inventario_menajes", :action => "modificar_elemento_inventario" %>" name="cantidad" data-original-title="Ingrese cantidad"><%= rim.cantidad %></a>
                <% elsif can? :read, RenglonInventarioMenaje %>
                  <%= rim.cantidad %>
                <% end %>
              </td>
              <td><%= rim.tipo_de_menaje %></td>
              <!--inventario_menajes#quitar_elemento_inventario-->
              <% if can? :destroy, RenglonInventarioMenaje %><td><a href="<%= url_for :controller => "inventario_menajes", :action => "quitar_elemento_inventario", :idElementoInventario => rim.id %>" onclick="return confirm('Realmente desea eliminar?')"> <span class="badge badge-important"> eliminar </span></a></td><% end %>
            </tr>
          <% end %>
          <% @renglon_inventario_menaje.each do |rim| %>
            <script type="text/javascript">
               $('#cantidad_<%= rim.id%>').editable({
                  type: 'text',
                  pk: 1,
                  url: '#',
                  title: 'Ingrese cantidad',
                  mode: 'inline'
               });
            </script>
          <% end %>
          </table>
          <br />

          <% if can? :create, RenglonInventarioMenaje %><a href="#myModal" role="button" data-toggle="modal"><span class="badge badge-success">Agregar menaje</span></a><% end %>
      </div>
   </div>
  </div>
</div>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Agregar Menaje al Inventario</h3>
  </div>
  <div class="modal-body">
    <form action="<%=url_for :controller => "inventario_menajes", :action => "agregar_elemento_inventario"%>" >
      <input type="hidden" id="idInventario" name="idInventario" value="<%=@inventario_menajes.id%>">
      <input type="text" id="cantidad" name="cantidad" placeholder="cantidad" class="input-mini">
      <select id="tipo_de_menaje" name="tipo_de_menaje">
        <% TipoDeMenaje.all.each do |tdm|%>
          <option value="<%= tdm.id %>"><%= tdm %></option>
        <% end %>
      </select>
      <input type="submit" value="agregar al inventario" class="btn btn-primary">
    </form>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
  </div>
</div>

app/views/inventario_menajes/new.html.erb
<h1>Agregar inventario_menaje</h1>

<%= render 'form' %>

<%= link_to 'atras', inventario_menajes_path %>

app/views/inventario_menajes/show.html.erb
<p>
  <b>Escuela:</b>
  <%= @inventario_menaje.escuela_id %>
</p>

<p>
  <b>Ultima modificacion:</b>
  <%= @inventario_menaje.ultima_modificacion %>
</p>


<%= link_to 'editar', edit_inventario_menaje_path(@inventario_menaje) %> |
<%= link_to 'atras', inventario_menajes_path %>