config/routes.rb
Mysecurity::Application.routes.draw do
scope "soft/nutriendo" do

  resources :inventario_menajes

  resources :inventario_equipamientos

  resources :tipo_de_menajes

  resources :tipo_de_equipamientos

  resources :escuelas

  resources :localidads

  resources :role_permissions

    devise_for :users, :path => 'user'

    resources :roles
    resources :users

  match 'inventario_menajes/inventarios/listado_escuela/:idEscuela' => 'inventario_menajes#listado_escuela' 
  match 'inventario_menajes/inventarios/agregar_elemento_inventario' => 'inventario_menajes#agregar_elemento_inventario'
  match 'inventario_menajes/inventarios/quitar_elemento_inventario/:idElementoInventario' => 'inventario_menajes#quitar_elemento_inventario'
  match 'inventario_menajes/inventarios/modificar_elemento_inventario/' => 'inventario_menajes#modificar_elemento_inventario'

  match 'inventario_equipamientos/inventarios/listado_escuela/:idEscuela' => 'inventario_equipamientos#listado_escuela' 
  match 'inventario_equipamientos/inventarios/agregar_elemento_inventario' => 'inventario_equipamientos#agregar_elemento_inventario'
  match 'inventario_equipamientos/inventarios/quitar_elemento_inventario/:idElementoInventario' => 'inventario_equipamientos#quitar_elemento_inventario'
  match 'inventario_equipamientos/inventarios/modificar_elemento_inventario/' => 'inventario_equipamientos#modificar_elemento_inventario'

  root :to => "escuelas#index"

end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Nutriendo Chubut</title>
  <%= stylesheet_link_tag    'application' %>
  <%= stylesheet_link_tag    params[:controller] %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag params[:controller] %>
  <%= csrf_meta_tags %>
 
  
  <%= csrf_meta_tags %>
  <%= yield(:head)%>

</head>
<body>
	<div class="container">
	<div id="navbar-example" class="navbar navbar-static">
	  <div class="navbar-inner">
	    <div class="container" style="width: auto;">
	      <a class="brand" href="<%= url_for root_path %>">&nbsp;&nbsp;&nbsp;Nutriendo Chubut</a>
	      <ul class="nav" role="navigation">
	       	
	       	<% if user_signed_in? then %>
		       <li class="dropdown">
		          <a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown">Nutriendo Chubut <b class="caret"></b></a>
		          <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
		           	<li><%=link_to "Escuelas", escuelas_path, :tabindex => "-1"%></li>
		          </ul>
		        </li>
	        	
	        <!-- ACCESO ADMINISTRADOR-->
	        	<% if current_user.role? :admin then %>
		        <li class="dropdown">
		          <a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown">Configuraci&oacute;n <b class="caret"></b></a>
		          <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
		           	<li><%=link_to "Escuelas", escuelas_path, :tabindex => "-1"%></li>
		        	<li><%=link_to "Tipo de Menajes", tipo_de_menajes_path, :tabindex => "-1"%></li>
		        	<li><%=link_to "Tipo de Equipamiento", tipo_de_equipamientos_path, :tabindex => "-1"%></li>
		        	<li><%=link_to "Localidades", localidads_path, :tabindex => "-1"%></li>
		          </ul>
		        </li>
		        <li class="dropdown">
		          <a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
		          <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
		           	<li><%=link_to "Usuarios", users_path, :tabindex => "-1"%></li>
		           	<li><%=link_to "Roles", roles_path, :tabindex => "-1"%></li>
		          </ul>
		        </li>
		        <% end %>
	        <% end %>
	      </ul>
	      <!-- INFORMACION DE LOGGING -->
	      <ul class="nav pull-right">
	        <li id="fat-menu" class="dropdown">
	          <% if user_signed_in? %>
		          <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">Bienvenido: <%= current_user.email %> <b class="caret"></b></a>
		          <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
		          	<li><%=link_to "Mi cuenta", edit_user_registration_path, :tabindex => "-1"%></li>
		            <li class="divider"></li>
		            <li><%= link_to 'Salir', destroy_user_session_path, :method => :delete, :tabindex => "-1" %></li>            
		          </ul>
		      <% else %>
		          <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">No ha iniciado sesion<b class="caret"></b></a>
		          <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
		          	<li><%= link_to "Iniciar Sesion", new_user_session_path , :tabindex => "-1" %></li> 
		          	<li class="divider"></li>
		            <li><%= link_to "Registrar", new_user_registration_path, :tabindex => "-1"%></li>           
		          </ul>
			  <% end %>
	        </li>
	      </ul>
		  <ul class="nav pull-right">
	        <li id="fat-menu">
	          <% if user_signed_in? -%>
	          	<% # TODO: agregar algo que permita ver la info de las instituciones que administra%>
	          	<%#if current_user.institucions then
	          	%>
	          	<!--  <li><a href="#" class="institucioninfo"><%#= current_user.institucion 
	          	  	%></a></li>
		          -->
		        <%# end 
		        %>
			  <% end %>
	        </li>
	      </ul>      
	    </div>
	  </div>
	</div> 									

	<div class="row"> 

		<div class="span12">
			<div class="container">
			   <% if flash[:error] then %>
			   	<div class="alert alert-error">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<h4>Error!</h4>
					<%= flash[:error]%>
	    		</div>
			   <% end %>
			   <% if alert then %>
	       		<div class="alert alert-block">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<h4>Advertencia!</h4>
					<%= alert %>
				</div>	       		
			   <% end %>
			   <% if notice then%>   
			       <div class="alert alert-info">
	    				<%= notice%>
	    		   </div>
	    	   <% end %>
	    	   <%= yield :menu %>
			   <%= yield %>
			</div>
		</div>
	</div>
	</div>
	<%= yield :scripts %>
</body>
</html>